version: "3"
services:
#  main:
#    container_name: main
#    build:
#      context: .
#    env_file:
#        - .env
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - ${APP_PORT}:3000
#    command: npm run start
#    depends_on:
#      - postgresql
#    restart: always

  postgresql:
    container_name: postgres
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
